// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu69L79JB0t8b1qiBAbFd2TVYErPK3B3Y',
    appId: '1:881963733279:web:2a66a6920938eb5d17e02a',
    messagingSenderId: '881963733279',
    projectId: 'easytalk-fcc5e',
    authDomain: 'easytalk-fcc5e.firebaseapp.com',
    storageBucket: 'easytalk-fcc5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFtI7peK0iPoAti9sTm-EsBtjotTiKCs',
    appId: '1:881963733279:android:8d89f4c86a691b4417e02a',
    messagingSenderId: '881963733279',
    projectId: 'easytalk-fcc5e',
    storageBucket: 'easytalk-fcc5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfXM71sulXiV7YeYhDVdQFTQugQ7P21nU',
    appId: '1:881963733279:ios:c10397f56ae0c37c17e02a',
    messagingSenderId: '881963733279',
    projectId: 'easytalk-fcc5e',
    storageBucket: 'easytalk-fcc5e.firebasestorage.app',
    iosBundleId: 'com.example.easyTalk',
  );
}
